---
- hosts: nodes
  gather_facts: no
  tasks:
    - name: Atualiza o SO completo
      yum:
        name: '*'
        state: latest



- hosts: nodes
  gather_facts: no
  tasks:
    - name: Adiciona Entrada no arquivo hosts
      blockinfile:
        dest: /etc/hosts
        block: |
          192.168.1.19 RKE-BASTION.HOMELAB.LOCAL 
          192.168.1.20 RKE-MASTER0.HOMELAB.LOCAL
          192.168.1.21 RKE-WORKER0.HOMELAB.LOCAL
          192.168.1.22 RKE-WORKER1.HOMELAB.LOCAL

    - name: Cria usuario para administrar cluster
      user:
        name: admincluster
        comment: Admin do Cluster

     # O Usuário deve fazer parte de um grupo onde não será necessário senha 
    - name: Adiciona o usuario admincluster ao grupo Wheel
      user: name=admincluster groups=wheel append=yes state=present createhome=yes


      ## O Usuário deve fazer parte de um grupo onde não será necessário senha
    - name: Permite grupo Wheel sem senha
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'



    ### Definindo a senha do usuário administrador do cluster 
    - name: Define senha do usuario (Tem que ser um hash e preciso usar o python para gerar o Hash)
      become: yes
      user:
        name: admincluster
        comment: "Admin do cluster"
        password: $6$INxDHuVqvGzKOB90$f2CjwN4jDwq1OLspYU2jhuY34aTOzvlWpejEftggwhaIG7hHgIc/ze.ohF3tu4Rxj77EmK9eo0CgurHrBZqTy0

   ### No Kubernetes se faz necessário desativar SWAP  
    - name: Parametrização de SO para o K8s
      command: "{{ item }}"
      become: yes
      with_items:
        - sed -i.bak -r 's/(.+ swap .+)/#\1/' /etc/fstab
        - swapoff -a
        - touch /etc/sysctl.d/k8s.conf
        - sysctl --system


  ### Para manter tudo em sincronia inclusive requisito de certificado é importante manter a hora certa

    - name: Instalar Pacote ntp NTP
      yum: name=ntp state=installed
      tags: install 
     

   ## Usa um template para o servidor de NTP deve-se criar dentro da pasta handler o restart
- hosts: all
  gather_facts: no
  tasks: 
     
    - name: Escreve o ntp.conf com os endereços do Observatorio Nacional
      template: src=ntp.conf.j2 dest=/etc/ntp.conf mode=644 owner=root group=root
      tags: ntp
      notify: 
           restart ntp
  handlers:
       - name: restart ntp
         service:
           name: ntpd
           state: restarted

- hosts: all
  gather_facts: no
  tasks:
    - name: Forca a sincronizacao do NTP
      command: "{{ item }}"
      with_items:
        - ntpdate -u pool.ntp.br
        - timedatectl set-ntp 1
      tags: ajuste
 

- hosts: nodes
  gather_facts: no
  tasks:
    - name: Adiciona entrada de kernel 
      blockinfile:
        dest: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

- hosts: nodes
  gather_facts: no
  tasks:
    - name: Instala o docker somente nos nodes indicado no arquivo hosts com dois grupos criados admin e nodes
      shell: curl https://releases.rancher.com/install-docker/18.09.sh | sh
      tags: docker2   

    - name: Marca o docker para iniciar durante o boot
      systemd:
        name: docker
        state: started
        enabled: true


    - name: Adiciona Usuario admincluster ao grupo docker
      user:
        name: admincluster
        shell: /bin/bash
        groups: docker
        append: yes




- hosts: admin
  gather_facts: no
  tasks:
    - name: Baixando o rke para subir o cluster
      command: "{{ item }}"
      with_items:
        - wget https://github.com/rancher/rke/releases/download/v1.2.1/rke_linux-amd64
        - mv rke_linux-amd64 rke
        - mv rke /usr/local/bin/
        - chmod +x /usr/local/bin/rke
      tags: rke
 


 
